version: '3'
services:
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    container_name: backend-container
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: db-postgres
      DATABASE_PASSWORD: 123123
      APPLICATION_PORT: 8080

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    container_name: fe_container
    ports:
      - 8080:8080
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
